### ISSUE TITLE
Continue Reading link not expanding article

### ISSUE THREAD

**Issue by tvories** [Lednerb/bilberry-hugo-theme#208]
## Configuration
- bilberry version: master
- hugo version: 0.72.0
- web server: nginx
- web browser: google chrome and firefox
- direct post to my website with the issue: https://taylorvories.com/articles/raspi-realmd/

## Issue
I have an article that has a continue reading link but when I click the link, it never expands the article.  Setting `noSummary: true` fixes the issue, but then I don't get the summary view on long articles.

If I start at my homepage and I click on the article, this is what I see:
![image](https://user-images.githubusercontent.com/13934524/83453183-44946380-a417-11ea-9942-c721c04091f8.png)

When I click the Continue Reading, nothing happens:

![continuereading](https://user-images.githubusercontent.com/13934524/83453620-0c415500-a418-11ea-8094-1ff6ff81295c.gif)

Snippet of article:

```
---
title: "Join Raspberry Pi to Active Directory (Rasbpian) Using Realmd"
date: "2016-11-08T17:56:33-07:00"
# noSummary: true
categories:
    - "article"
tags:
    - "Raspberry Pi"
    - "Active Directory"

aliases:
    - /posts/raspi-realmd/
    - /post/raspi-realmd/

featuredImage: "/img/pi.jpg"
resizeImage: true
cardbackground: "#e74c3c"

author: Taylor Vories
    # image: "/img/tavatar.png"
---

I've been working with [Ansible](http://ansible.com) lately so I've been trying to automate everything I can.  I work with Linux systems in AD, so I've been trying to figure out a way to auto deploy and join to my domain.  Since I had a few Pis laying around, I decided to set them up on my domain as well.  I will also include a link to my [Ansible playbook](/post/ansible-realmd/) that automates this process.  This guide assumes you have updated your apt repositories recently.
.........
```

**Comment by Lednerb** [comment]
Hey @tvories 

I will be working on this at the weekend.

If I understand the issue correctly, the "Continue Reading" link is also shown on the article's single page instead only on the homepage and taxonomies view?

**Comment by tvories** [comment]
> If I understand the issue correctly, the "Continue Reading" link is also shown on the article's single page instead only on the homepage and taxonomies view?

I'm not sure which view is the single page view and which view is the taxonomies view.  The main page view shows the continue reading as well as the direct article link if that's what you're asking.

**Comment by Lednerb** [comment]
Exactly, thanks.

**Comment by frigi83** [comment]
I have the same issue as @tvories  with a new generated article. On my laptop with the ubuntu PPA version of Hugo the problem was the building, test server (`hugo server -D`) was ok.

After that I have installed directly from the snap and now I have version `Hugo Static Site Generator v0.72.0 linux/amd64 BuildDate: 2020-05-31T18:06:12Z`. With this version it work's.

**Comment by frigi83** [comment]
@tvories do you delete the public directory or do you just run the `hugo` command?

In GitHub Actions I need to deploy my hugo site 2 times (between I delete all the public files) and after it works.

The strange thing is that my problem was only with the latest created post.

**Comment by tvories** [comment]
I did not try deleting my public files.  I'll give that a shot.

**Comment by Lednerb** [comment]
Hey @tvories 

I've tried to reproduce the issue with a fresh hugo site using the theme and it's example content, but could not reproduce the error with the following `hugo` version:

```
Hugo Static Site Generator v0.72.0-8A7EF3CF linux/amd64 BuildDate: 2020-05-31T12:07:45Z
```

Next I will try to reproduce this with windows, maybe it's OS-related?

**Comment by Lednerb** [comment]
Indeed, I can reproduce this error on Windows 10 using version:

```
Hugo Static Site Generator v0.72.0-8A7EF3CF windows/amd64 BuildDate: 2020-05-31T12:08:42Z
```

I think it's not related to this theme but to `hugo` in general?
I will check the `hugo` repo issues now...

**Comment by Lednerb** [comment]
@tvories it seems that this issue was indeed introduced in the latest hugo versions.

I've tried this version on Windows without any issues.

```
Hugo Static Site Generator v0.61.0-9B445B9D windows/amd64 BuildDate: 2019-12-11T08:29:13Z
```

Can you please verify this?
We can also open an issue in the hugo repository, so it get's globally fixed then.

**Comment by tvories** [comment]
I have tried building with hugo v 0.61.0 and my site won't build:

```
hugo
Building sites … ERROR 2020/06/08 09:34:29 render of "page" failed: "C:\Users\taylor\gits\taylorvories.com\themes\bilberry-hugo\layouts\_default\single.html:14:24": execute of template failed: html/template:_default\single.html:14:24: no such template "partials/commento.html"        
ERROR 2020/06/08 09:34:29 render of "page" failed: "C:\Users\taylor\gits\taylorvories.com\themes\bilberry-hugo\layouts\_default\single.html:14:24": execute of template failed: html/template:_default\single.html:14:24: no such template "partials/commento.html"
ERROR 2020/06/08 09:34:29 render of "page" failed: "C:\Users\taylor\gits\taylorvories.com\themes\bilberry-hugo\layouts\_default\single.html:14:24": execute of template failed: html/template:_default\single.html:14:24: no such template "partials/commento.html"
Total in 790 ms
Error: Error building site: failed to render pages: render of "page" failed: "C:\Users\taylor\gits\taylorvories.com\themes\bilberry-hugo\layouts\_default\single.html:14:24": execute of template failed: html/template:_default\single.html:14:24: no such template "partials/commento.html"
```

I tried a few previous versions and it built successfully on v 0.67.1 and it builds but I am still getting the same issue.  I delete my public folder each time and fully regenerate it and I get the same problem.

**Comment by Lednerb** [comment]
Please pull the latest changes. I've fixed that compatibility issue yesterday.

**Comment by tvories** [comment]
I have pull the latest changes as of today and rebuilt using hugo 0.72.0 and I am still having this issue.  I have built with WSL Ubuntu as well as Windows hugo.

**Comment by omerakgoz34** [comment]
This issue also happening for me but randomly :/

Hugo Static Site Generator v0.73.0/extended windows/amd64
Bilberry Hugo Theme github master

**Comment by Lednerb** [comment]
Hey @omerakgoz34 

please try to use the version 0.62 with the latest version from the `master` branch and give me feedback if it also happens there.

Maybe we can reproduce and fix this issue ...

**Comment by omerakgoz34** [comment]
I tried with hugo v0.62.0 and latest master version of theme but it's still same.
I have no idea about why this is happening :(

**Comment by omerakgoz34** [comment]
+ only for some pages

**Comment by Lednerb** [comment]
Okay, than I assume that it's a theme-related issue

Maybe there is a variable that is not initilaized / resetted correctly and depending on the last hugo status or the order in which the pages are generated, varying results are produced.

**Comment by Lednerb** [comment]
Today I was able to reproduce the error via GitHub Action AutoDeploy.

I will investigate further and release a new version of the theme after this issue is fixed.

**Comment by Lednerb** [comment]
I assume I've found the reason for this bug.

According to this blog post:
https://harmstyler.me/posts/2019/how-to-pass-variables-to-a-partial-template-in-hugo/

> Partials, however, have one serious limitation, they’re cached during the build of a given page (or scope). Once a partial has been created, no outside logic can adjust what the partial returns (for the page). 

Maybe there is something like a cache-race-condition when building the `default-content.html` partial twice (one time for the `list.html` layout and one time for the `single.html` layout).

If this assumption is correct, the import of the `default-layout.html` has to be refactored.

**Comment by Lednerb** [comment]
I've verified that this is the case via small changes and a quick python script to check for consistency.
Now trying to fix this. Stay tuned.

**Comment by Lednerb** [comment]
Problem should be fixed in the latest `master` version now.

It was a caching issue caused by the DRY-Code for including the `default-content` partial within another partial.

**Comment by Lednerb** [comment]
Sorry guys, this makes me crazy... Not fixed yet...

**Comment by Lednerb** [comment]
Asking for further help in the forums:
https://discourse.gohugo.io/t/handle-partial-in-partial-caching-block-inheritance/27142

**Comment by Lednerb** [comment]
Fixed now.
I've decided to refactor the partials and to remove the `.Scratch` part as it produces errors when multiple partials are involved as it seems to me that the partials are rendered / cached independently of each other.
